### PR TITLE
Restructure seuronbot

### PR DESCRIPTION
**Pull request by ranlu**
Split `slack_bot.py` into smaller modules. As the first step, move the code interacts directly with slack(rtm) into a separate files, and replace the big `dispatch_command` function with individual functions registered by decorators, the decorators also contain metadata of the command defined, so we can use the information to generate a list of command supported.

### CODE REVIEW

**Comment by ranlu** [comment]
@nicholasturner1, can you take a look at the synaptor related commands to add some description to them. We can also use this opportunity to make the commands more consistent, maybe change `update parameters` to `update segmentation parameters`. Feel free to make other changes if you see fit.

**Comment by ranlu** [comment]
@nicholasturner1, I merged [your pr](https://github.com/seung-lab/seuron/pull/25). I also added a new `update parameters` command, it tries to guess the type of the parameters based on the docker image. I do not know if we can extend it to recognize synaptor parameters as well, maybe just check if the input is toml? There could be a general `run` command to trigger the runs based on the parameters uploaded, I have not implement that yet.

**Comment by nicholasturner1** [comment]
> @nicholasturner1, I merged [your pr](https://github.com/seung-lab/seuron/pull/25). I also added a new `update parameters` command, it tries to guess the type of the parameters based on the docker image. I do not know if we can extend it to recognize synaptor parameters as well, maybe just check if the input is toml? There could be a general `run` command to trigger the runs based on the parameters uploaded, I have not implement that yet.

That sounds good. The synaptor parameters also include a docker image. In #21 they also use a json dict, so this check function would be very similar. Could we just check the value of the docker image instead of the field name?

**Comment by ranlu** [comment]
OK, I will merge the redis pr today. I prefer to check the name of the key instead of matching the value. Technically it is possible for users to use their own image with arbitrary names, but we have control over the name of the keys. Besides I think it is already tricky to check images hosted by google with the long urls. What do you think?

**Comment by nicholasturner1** [comment]
Maybe you're right. I think you'd almost have to be intentionally misleading to not use the name of the tool you want to use in your image name, but every option for passing the image uses the `${package_name}_image` convention (except segmentation), so that works well.

**Comment by ranlu** [comment]
Hmm, when you suggested matching the image name, did  you also plan to use something like `WORKER_IMAGE` in all parameter files? otherwise I do not see the advantage of matching image names. We changed image names in the past, seuron used to be air-tasks, and abiss was seuron-worker, that is the reason I am not so thrilled about using the image names. We could also explicitly require use to specify the type of the job, with a field like `RUN_TYPE` or `JOB_TYPE`, but I found guessing from the image field is quite reliable already.

**Comment by nicholasturner1** [comment]
I was agreeing with you in that last message. I now think that matching by the field name (key) is better.

**Comment by ranlu** [comment]
I tested the rebased code, I think we can conclude this pr and add examples and other features with pr in the future. @nicholasturner1, is it ok I merge this one?

**Comment by nicholasturner1** [comment]
Sounds great! Merge away!

**Pull request merged**
